<?php

/**
 * @file
 * Contains dddlx_users.module.
 */

/**
 * Implements hook_ENTITY_TYPE_presave().
 *
 * Add the attendee role by default to new users.
 */


/**
 * Implements hook_entity_extra_field_info().
 */
function dddlx_users_entity_extra_field_info() {
  $extra = [];

  $extra['user']['user']['form'] = [
    'gender_info' => [
      'label' => new \Drupal\Core\StringTranslation\TranslatableMarkup('Gender explanation info'),
      'description' => new \Drupal\Core\StringTranslation\TranslatableMarkup('The gender explanation text below the gender field.'),
      'weight' => 0,
    ],
  ];

  return $extra;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function dddlx_users_form_user_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // We add the states rules for the field field_gender_write_in:
  if (isset($form['field_gender_write_in'])) {
    $form['field_gender_write_in']['#states'] = [
      'visible' => [
        ':input[name="field_gender"]' => ['value' => 'other'],
      ],
    ];

    if (isset($form['field_gender'])) {
      $form['gender_info'] = ['#markup' => new \Drupal\Core\StringTranslation\TranslatableMarkup(
        'The purpose of this information is to get data about the diversity of the
       conference. It won\'t be public on your profile, will be only used by 
       the organization team and will only be shared publicly in aggregated ways.'
      )];
    }
  }
}
