version: 1.1.0

services:
  - php:
      version: 7.1

events:
  build:
    steps:
      - get-core:
          type: script
          script:
            # Build non-development composer packages.
            - composer global require hirak/prestissimo
            - composer install --no-interaction --no-dev --optimize-autoloader
