<?php

/**
 * @file
 * Contains ddd_attendee.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ddd_attendee_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ddd_attendee module.
    case 'help.page.ddd_attendee':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Drupal Dev Days Attendee module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ddd_attendee_theme() {
  return [
    'ddd_attendee' => [
      'render element' => 'children',
    ],
  ];
}
